### ISSUE TITLE
no images in this image list

### ISSUE THREAD

**Issue by pierrenel** [ecmendenhall/wgif#10]
Hi there,

Your björk example: 

`wgif https://www.youtube.com/watch?v=1A78yTvIY1k bjork.gif --start 00:03:30 -d 2 -f 18 --width 350`

works perfectly, but when I try:

`wgif https://www.youtube.com/watch?v=deFDlB8RiNg fish_grease.gif --start 00:00:13 -d 3 -f 20 --width 350`

I get:

```
no images in this image list
/Users/pierre/.rvm/gems/ruby-2.0.0-p247/gems/wgif-0.2.0/lib/wgif/gif_maker.rb:8:in `coalesce'
/Users/pierre/.rvm/gems/ruby-2.0.0-p247/gems/wgif-0.2.0/lib/wgif/gif_maker.rb:8:in `make_gif'
/Users/pierre/.rvm/gems/ruby-2.0.0-p247/gems/wgif-0.2.0/lib/wgif/cli.rb:80:in `block in make_gif'
/Users/pierre/.rvm/gems/ruby-2.0.0-p247/gems/wgif-0.2.0/lib/wgif/cli.rb:92:in `rescue_errors'
/Users/pierre/.rvm/gems/ruby-2.0.0-p247/gems/wgif-0.2.0/lib/wgif/cli.rb:74:in `make_gif'
/Users/pierre/.rvm/gems/ruby-2.0.0-p247/gems/wgif-0.2.0/bin/wgif:4:in `<top (required)>'
/Users/pierre/.rvm/gems/ruby-2.0.0-p247/bin/wgif:23:in `load'
/Users/pierre/.rvm/gems/ruby-2.0.0-p247/bin/wgif:23:in `<main>'
/Users/pierre/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `eval'
/Users/pierre/.rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:15:in `<main>'
```

Thanks!

**Comment by Pluto1010** [comment]
How did you solve this?

**Comment by simonewebdesign** [comment]
As @ecmendenhall said, changing one of the parameters will work. I did solve it that way at the time.
